# Generated by Django 2.2.1 on 2020-01-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0003_auto_20200114_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
        migrations.AlterField(
            model_name='problem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp_app.Tag'),
        ),
    ]
