# Generated by Django 2.2.1 on 2020-01-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0004_auto_20200115_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
    ]
