# Generated by Django 2.2.1 on 2020-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0002_problem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_pic', models.ImageField(upload_to='author_pics')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='rating',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ManyToManyField(to='cp_app.Author'),
        ),
    ]
