# Generated by Django 2.2.1 on 2020-01-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0005_auto_20200115_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cp_app.Author'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tag',
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(to='cp_app.Tag'),
        ),
    ]
